### ISSUE TITLE
Pykwalify will not work for us

### ISSUE THREAD

**Issue by rgaiacs** [sdruskat/citation-file-format#12]
When working on #11, I discovered that Pykwalify doesn't support a list of pre-defined schemas, see https://sourceforge.net/p/kwalify/feature-requests/10/, which make impossible to have some attributes limited to some Work Types, for example `commit` clear make sense for software and can make sense for `manual` (the manual of a software) but I it doesn't make sense for me to `conference`.

**Comment by sdruskat** [comment]
Thanks for testing this!

Not sure if I find this to be problematic as I thought about just having a rather loose schema checking for data types, etc.

A strict schema would be a nice thing to have, but if it won't work I don't think that's a huge problem. That's why I included the following in the "Concepts" section.

> in CFF, all available keys can be used for all Work Types. CFF leaves reasonability of use with format users and providers of tooling, such as conversion software for CFF and other formats.

Keeps it hackable as well (like BibTeX) for features which we haven't thought of/not included yet ;).

**Comment by sdruskat** [comment]
On other words, enforcing the (implicit) schema should be a feature of the tooling. Should be explicitly described in the "Schema" section.

Perhaps we can introduce a stricter schema in a later version?

**Comment by rgaiacs** [comment]
> Perhaps we can introduce a stricter schema in a later version?

Works for me.

**Comment by sdruskat** [comment]
Closing this and tracking in #14.
